title: FOLIO Developer Curriculum
baseurl: "/curriculum"
theme: jekyll-theme-minimal
google_analytics: UA-79833310-3
repository: folio-org/curriculum
exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - playbooks
